billie: config.fs: Checkout changes from CLO
danascape/device_oneplus_billie pull request #4
Opened 2022-10-17 09:57 UTC by kawaaii

- Checked out changes from tag : LA.UM.9.12.r1-14700.03-SMxx50.QSSI12.0

Signed-off-by: kawaaii <kawaaii@nocturn9x.space>
Change-Id: I21bd5e07f6d1125081db57d8a23198b620d27eda

2022-10-17 15:38 UTC, danascape requested changes
'system/vendor/' is symlinked with 'vendor/' so there is no need to keep both of the mappings. Kindly clean then up.

2022-10-18 07:41 UTC, saalim-quadri approved these changes
Drop the wcnss_filter entry, the binary does not exist.

2022-10-18 07:42 UTC, danascape requested changes
wcnss_filter mapping is unneeded

2022-10-19 16:19 UTC, danascape commented on config.fs
> +[system/bin/cnss-daemon]
This doesnt exist in system

2022-10-21 18:04 UTC, danascape approved these changes

2022-10-21 18:04 UTC, merged